Go zbchaos worker
zeebe-io/zeebe-chaos pull request #191
Opened 2022-10-12 08:48 UTC by oleschoenburg

This adds a new command `zbchaos worker` that starts a worker that listens to `zbchaos` jobs from testbench and executes them. To execute, we don't spawn a new process and instead use corba to directly call the command with the provider arguments.

2022-10-12 08:49 UTC, oleschoenburg commented on go-chaos/go.sum
> +github.com/camunda-cloud/zeebe/clients/go v1.3.14 h1:NjvinpaQIUlQQbfseqWFrCGkFB8SnbrG3fNongTzac8=
:question: I'm a bit confused about this one, without fixing the checksum I can't download the dependencies. Not sure why the checksum would have changed.

2022-10-12 08:55 UTC, oleschoenburg commented on go-chaos/go.sum
> +github.com/camunda-cloud/zeebe/clients/go v1.3.14 h1:NjvinpaQIUlQQbfseqWFrCGkFB8SnbrG3fNongTzac8=
Yeah, CI says that the issue is on my side. I've fixed it by cleaning up my $GOPATH. I'll remove the commit from here.

2022-10-12 08:55 UTC, oleschoenburg commented on go-chaos/go.sum
> +github.com/camunda-cloud/zeebe/clients/go v1.3.14 h1:NjvinpaQIUlQQbfseqWFrCGkFB8SnbrG3fNongTzac8=
Actually nevermind, I still have the same issue after cleaning up $GOPATH. I'll upgrade to 8.1 then.

2022-10-12 10:44 UTC, oleschoenburg commented
I had a bunch of problems trying to keep go.sum up  to date with go.mod so I upgraded to go 1.19 too which solved the issue for me :shrug:

2022-10-12 11:07 UTC, Zelldon commented
I use also g1.19 locally :+1:

2022-10-12 12:00 UTC, oleschoenburg commented
Then I'd say it's ready for review :)

2022-10-13 06:35 UTC, Zelldon requested changes
Awesome thanks for taking the initative @oleschoenburg 
Great work and idea with running the worker as own command. I first had in mind to have a separate application or something which executes the worker, but this might be even better :+1: 

Please see my comment regarding the env vars. Lets fix this first, before merging :)

2022-10-13 06:35 UTC, Zelldon commented on go-chaos/cmd/worker.go
> +		AuthorizationServerURL: os.Getenv("TESTBENCH_AUTHORIZATION_SERVER_URL"),
:x: Would be great if we could leave testbench out here. Can you check whether the go client already supports env vars for the cloud client? Maybe this is not event necessary.

The testbench env vars can then be injected into the docker image for example

2022-10-13 06:35 UTC, Zelldon commented on go-chaos/cmd/worker.go
> +}
Thats great :rocket:

2022-10-13 06:35 UTC, Zelldon commented on go-chaos/go.mod
> +go 1.19
:rocket:

2022-10-13 12:25 UTC, Zelldon approved these changes
Super Thanks :+1:

2022-10-13 12:27 UTC, merged